services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    container_name: yanakilla-zinc
    restart: unless-stopped
    environment:
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: Complexpass#123
      ZINC_DATA_PATH: /data
    ports:
      - "4080:4080"
    volumes:
      - zinc-data:/data

volumes:
  zinc-data:
